### ISSUE TITLE
Waiting for Events

### ISSUE THREAD

**Issue by sankdeveloper** [LayTec-AG/Plotly.Blazor#91] opened 2021-05-25 12:49 UTC

**Comment by sean-mcl** [comment] 2021-05-25 12:50
Hi, feel free to contribute. :)

**Comment by riboyama** [comment] 2021-05-31 12:28
If you really need Events, try [this workaround from sean himself](https://github.com/LayTec-AG/Plotly.Blazor/issues/27#issuecomment-720426613)

**Comment by sean-mcl** [comment] 2021-07-01 15:36
Duplicate of #27

**Closed** 2021-07-01 15:36 UTC
Labels: future work
